<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoload781c4547a8a27b6fa5d144d420cb36a4($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'email' => '/Email.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoload781c4547a8a27b6fa5d144d420cb36a4', true);
// @codeCoverageIgnoreEnd
